Gerber Gear Prybrid Utility Knife with Pry Bar
https://amzn.to/4ezn2rn

= Lights

Coast KL20R 380 Lumen EDC Rechargeable Lightweight LED Keychain Flashlight, Black
https://amzn.to/3XzTOl7

Coast PX1 565 Lumen Pure Beam Focusing LED Flashlight with Twist Focus and Adjustable Pocket Clip
https://amzn.to/3XT2OmV

Coast GX20 1200 Lumen Waterproof Alkaline-Dual Power LED Flashlight with Twist Focus, Anti-Roll Cap and Textured Handle - Compatible with 4 x AAA Batteries (Included) or ZX750 Rechargeable Battery
https://amzn.to/4e9coYx

COAST HX5 410 Lumen LED Flashlight, Pure Beam Focusing, Slide Focus, Pocket Clip, Weatherproof, Pocket Sized, Battery Included, Black.
https://amzn.to/4guKW99

COAST PX20 Dual Color 400 Lumen LED Flashlight
https://amzn.to/4dh1IWe

COAST XP11R 2600 Lumen USB-C Rechargeable LED Flashlight with SLIDE FOCUS and PURE BEAM Focusing Optic, 4 Light Modes
https://amzn.to/4eOLcOL

Coast AAA USB-C Rechargeable Batteries
https://amzn.to/47CbQaT

OLIGHT Oclip Rechargeable EDC Flashlight
https://amzn.to/3XxvvEr

OLIGHT I3T 2 EOS Pocket EDC Flashlight, 200 Lumens Compact Bright Handheld Flashlights, Dual-Output Tail Switch Light with AAA Battery and Two-Way Pocket Clip for Camping and Hiking (Black)
https://amzn.to/47H9RCs

OLIGHT I3T EOS 180 Lumens Dual-Output Slim EDC Flashlight for Camping and Hiking, Tail Switch Flashlight with AAA Battery
https://amzn.to/3znlWzX

Streamlight 66318 MicroStream 45-Lumen Everyday Carry Pocket Flashlight with AAA Alkaline Battery, Black
https://amzn.to/4ebOUBN

Streamlight 66118 Stylus Pro 100-Lumen Penlight with 2 AAA Alkaline Batteries, Black
https://amzn.to/3Y1z3QZ

BORUIT V3 Mini Powerful Keychain Flashlights with Red UV Blue Light,High Lumens 900LM USB-C Rechargeable Small Pocket EDC LED Flash Light-12 Modes,IP65 Waterproof,Tail Magnet
https://amzn.to/3B9Ge0r

BORUIT V20 LED Small Powerful EDC Flashlight with Clip,180°Head Swivels,1000LM USB C Rechargeable Mini Pocket Keychain Flash Light with Red COB Light-14 Mode,IP67,Magnetic,110DB Buzzer(Black)
https://amzn.to/4dkiLa2





= Pens

MUJI - 0.5mm Black Smooth Gel Ink Retractable Ballpoint Pen (10 Pieces)
https://amzn.to/4ewoA5f

Rite in the Rain Weatherproof Black Metal Clicker Pen - Black Ink (No. 97)
https://amzn.to/3MROkNG

Rite in the Rain Weatherproof Mechanical Pencil
https://amzn.to/3MSNJLO

Rite in the Rain Weatherproof Olive Drab and Flat Dark Earth Mini Bolt-Action Pens - Black Ink, 2 Pack (No. TAC20)
https://amzn.to/3XG0RsK

Everyman Military Super Matte Grafton Pen - New and Improved Premium EDC Pen
https://amzn.to/3XTJ5Cr

Zebra Pen M/F 701 Stainless Steel Mechanical Pencil and Ballpoint Pen Set, Fine Point, 0.7mm HB Lead and 0.8mm Black Ink, 2-Count Gift Set, Silver (10519)
https://amzn.to/3MVikIo

Zebra SB14-BK Sharbo X ST3 Multi-Functional Pen, Black
https://amzn.to/4dh0GcO

= Watch

Casio Men's Stainless Steel Quartz Resin Strap, Black, 22 Casual Watch (Model: MTP-S110-1AVCF), RED
https://amzn.to/4dhanIp

Casio Men's Solar Powered Japanese Quartz Watch with Resin Strap Green (Model: AQS810W-3AV)
https://amzn.to/47BlCub

G-Shock GA-2100-1A1 Black One Size
https://amzn.to/4dcXmQc

Casio Illuminator AE1500WH Series | 10-Year Battery | LED Backlight | 5-Alarms | 1/100 Sec Stopwatch | Men's Digital Watch
https://amzn.to/3Zx3UWn

Casio Men's STLS-110H-1B2CF Tough Solar Digital Display Quartz Black Watch
https://amzn.to/3Zx3WgX

= Knife

CIVIVI Sendy 3 In 1 Multitool Pocket Knife With Tweezers and Toothpick, Ben Petersen designed Folding Knife for EDC Camping Daily Use, Perfect Gifts for Men Women C21004A-1
https://amzn.to/4guLwDP

48-22-1505 Compatible with Milwaukee Fastback™ 6 in 1 Folding Utility Knife
https://amzn.to/3XRJUge

Milwaukee FASTBACK Folding Utility Knife w/Blade Multifunctionality, Red-black
https://amzn.to/3XMZMjT

= Multitool

LEATHERMAN, Skeletool, 7-in-1 Lightweight, Minimalist Multi-tool for Everyday Carry (EDC), Home, Garden & Outdoors, Black/Tan
https://amzn.to/4ddVGFW

LEATHERMAN, Wave+, Bit Driver Extender, Bit Kit Bundle
https://amzn.to/3XwDCRO

LEATHERMAN, Signal, 19-in-1 Multi-tool for Outdoors, Camping, Hiking, Fishing, Survival, Durable & Lightweight EDC, Made in the USA, Coyote Tan
https://amzn.to/4ew4Aj0


